### ISSUE TITLE
Add a button to revoke what you talk

### ISSUE THREAD

**Issue by longkunbetter** [proxoar/talk-web#30]
It is very practical to add a button which enables users to revoke their voice.
For example, after I click the 'Spacebar' to speak, a submit button and a cancel button are showed.
Users can use the cancel button to revoke.

**Comment by proxfly** [comment]
Thank you for highlighting this matter! As we near the completion of our core features, we're pivoting our attention towards enhancing the user experience, and the addition of this button is part of those improvements. 

By the by, we're in a rapid development phase and are always happy to welcome new contributors. If you're well-versed in React.js, we'd be delighted to receive a PR from you.

**Comment by proxfly** [comment]
Merged into main, and the background of the microphone has been adjusted for enhanced clarity.

![Image](https://github.com/proxoar/talk-web/assets/27894831/93e6f6f9-4054-4380-b4c4-065b70711ea0)
